baseURL = "https://nicoohr.github.io/fishbowl/"
languageCode = "en-us"
title = "Fishbowl"
theme="archie"
copyright = "© Nico Ohayon Rozanes"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="toggle"
	useCDN=false
	customCSS = ["css/sidenotes.css", "css/typography.css"]
	mainSections = ["posts"]

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/NicoOhR"

[[menu.main]]
name = "About"
pageRef = "/about"
weight = 1

[[menu.main]]
name = "More Matter"
url = "https://nicoohr.github.io/Sicarii/"
weight = 2

[[menu.main]]
name = "Tags"
pageRef = "/tags"
weight = 4

[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)'], ['$', '$']]
