baseURL = "https://nicoohr.github.io/fishbowl/"
languageCode = "en-us"
title = "Fishbowl"
theme="archie"
copyright = "© Nico Ohayon Rozanes"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="toggle"
	useCDN=false
	customCSS = ["css/sidenotes.css"]

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/NicoOhR"

[[menu.main]]
name = "About"
pageRef = "/"
weight = 1

[[menu.main]]
name = "More Matter"
url = "https://nicoohr.github.io/Sicarii/"
weight = 2

[[menu.main]]
name = "Tags"
pageRef = "/tags"
weight = 4
